function retval = randomRequest(theaterx,theatery,varargin)
    catalog = ItemFactory.getCatalog;
    isDelivery = (rand < .5);
    if nargin < 3
        retval = Request(randi(intmax),...
                         randomPoint(theaterx,theatery),...
                         ItemFactory.makeItem(catalog(randi(numel(catalog)))),...
                         'Me',...
                         1,...
                         now,...
                         now,...
                         randi(2),...
                         isDelivery,...
                         ~isDelivery);
        retval.item;
        retval.quantity;
    else
        varargin{1}.addRequest(randomPoint(theaterx,theatery),...
                               ItemFactory.makeItem(catalog(randi(numel(catalog)))),...
                               'Me',...
                               1,...
                               now,...
                               now,...
                               randi(2),...
                               isDelivery,...
                               ~isDelivery);
        retval = [];
    end
end