classdef ItemFactory
    %ITEMFACTORY 
    
    properties (Constant)
        itemTable = cell2struct(...
            {'Sterile Band',     'r',   1,        'Quadcopter',    1,        .1;...
             'Stabilizer',       'y',   1,        'Quadcopter',    1,        .1;...
             'Thrombolytics',    'k',   1,        'Quadcopter',    1,        .1;...
             'Carbamazepine',    'w',   1,        'Quadcopter',    1,        .1;...
             'Oral Airway',      'b',   1,        'Quadcopter',    1,        .1;...
             'Endotracheal Tube','y',   1,        'Quadcopter',    1,        .1;...
             'Thermal Camera',   'y',   1,        'Quadcopter',    1,        2;...
             'Thermal Blanket',  'c',   1,        'Quadcopter',    1,        2;...
             'Defibrillator',    'b',   1,        'Quadcopter',    1,        2;...
             'Sensory Animal',   'm',   1,        'Car',           1,        10;...
             'Robotic Arm',      'm',   1,        'Car',           1,        10;...
             'Robot ATLAS',      'm',   1,        'Car',           1,        10},...
                {'name',      'color' 'priority' 'carrier'      'volume'  'weight'},...
                                2);
    end
    
    methods (Static)        
        function retval = makeItem(name)
            t = ItemFactory.itemTable;   %g835097
            if strcmp(name,'empty')
                retval = t([]);
            else
                retval = t(strcmp({t.name},name));
            end                
        end
        
        function retval = getCatalog
            t = ItemFactory.itemTable;   %g835097
            retval = {t.name};
        end            
    end
    
end
